### ISSUE TITLE
Display only stack size?

### ISSUE THREAD

**Issue by clownshoe123** [alexanderhenne/external-plugins#8]
any chance the info box for the damage you do and true tile could be toggleable? I only want to see the stack number, nothing else. Thanks

**Comment by droza123** [comment]
I just wanted to second this suggestion. This is especially important as a suggestion because, when you are not barraging, the infobox still appears and says "Monkey Metrics plugin waiting for NPC damage." This takes up space, and makes it so that I need to turn the plugin on and off everytime I want to use it, as I don't want to see it when I am not using it. 
Please make the infobox toggleable (I don't really ever want to see it), or at least make it disappear automatically when it is just waiting for data, or after a certain amount of time with it not changing. Thanks!

**Comment by alexanderhenne** [comment]
This is implemented now
